cohort:
  name: MSE Studio
  semesters:
  - semester: Spring 2026
    dates:
      start: 1-12-2026
      end: 4-24-2026
      break:
        start: 2-28-2026
        end: 3-8-2026
      holidays:
      - 1-19-2026
      - 4-10-2026
  - semester: Summer 2026
    dates:
      start: 5-11-2026
      end: 7-30-2026
      holidays:
        - 7-2-2026
        - 7-3-2026
        - 6-19-2026
        - 5-22-2026
        - 5-25-2026
  - semester: Fall 2026
    dates:
      start: 7-24-2026
      end: 12-11-2026
      break: 
        start: 10-9-2026
        end: 10-19-2026
      holidays:
        - 9-7-2026
        - 11-3-2026
        - 11-25-2026
        - 11-26-2026
        - 11-27-2026
roster:
  - team: Troutans
    client: Troutwood
    members:
      - name: Noor Buchi
        andrewid: nbuchi
        email: nbuchi@andrew.cmu.edu
      - name: Doheon Hwang
        andrewid: doheonh
        email: doheonh@andrew.cmu.edu
      - name: Yoonme Hwang
        andrewid: yoonmeh
        email: yoonmeh@andrew.cmu.edu
      - name: Kanishk Kakar
        andrewid: kkakar
        email: kkakar@andrew.cmu.edu
      - name: Luke Kiebert
        andrewid: lkiebert
        email: lkiebert@andrew.cmu.edu
  - team: Logixians
    client: IRALogix
    members:
      - name: Saúl Alvarez Tapia
        andrewid: saula
        email: saula@andrew.cmu.edu
      - name: Li-Fu Chang
        andrewid: lifuc
        email: lifuc@andrew.cmu.edu
      - name: Arjun Nair
        andrewid: arjunnai
        email: arjunnai@andrew.cmu.edu
      - name: Jay Sun
        andrewid: jieyis
        email: jieyis@andrew.cmu.edu
      - name: Chawit Uviengchai
        andrewid: puviengc
        email: puviengc@andrew.cmu.edu
      - name: Kuan Wu
        andrewid: kuanlinw
        email: kuanlinw@andrew.cmu.edu
  - team: eParts
    client: eParts
    members:
      - name: Hrishikesh Bhardwaj
        andrewid: hrishikb
        email: hrishikb@andrew.cmu.edu
      - name: Ashritha Gonuguntla
        andrewid: agonugun
        email: agonugun@andrew.cmu.edu
      - name: Zheliang Liu
        andrewid: zhelianl
        email: zhelianl@andrew.cmu.edu
      - name: Jaivardhan Singh
        andrewid: jaivards
        email: jaivards@andrew.cmu.edu
